include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_relative_imports: true

analyzer:
  errors:
    prefer_relative_imports: warning
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - ios/SourcePackages/**

    